# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dc59a15b31cdc247a6f30d71ed867475f94793b16dc7792a13dbf808d0b0e8df51406018b01ea2497fa664022ab16bda8a6edda302dfa7a59e99f1875ebcafb6

test:
  secret_key_base: b9148ef93f3caef7cb7a343d55c9fa8b727f43f8af6b077fe259a1edf4f5e50d6704736f4d856f352764f120e124f0af56b656098ea09d33ab8fff1755caf823

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 7cdfac7d48667a37721eb9c15954575a98970490973b7df0697605120cd46e1dc361118062ae6403988e81d4e30ef0407b0bcd8eb3e1df2bc40b95a4ab215e1f
  #本机:
#  secret_key_base: b267f04f66d1ff318442aa933e4cfaf2412090b42ae1b43eee8001ee1e12be497e72ccc391b982523ed9507e3a3d024af7306a277561e24157924c2b0cfe1be2
#  secret_key_base: <%#= ENV["SECRET_KEY_BASE"] %>